[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
cache = true
cache_path = 'cache'
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
verbosity = 3

via_ir = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = 'long'
func_attrs_with_params_multiline = true
quote_style = 'double'
number_underscore = 'preserve'
multiline_func_header = 'params_first'